version: '3'
services:
  e-commerce:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    command: yarn run dev
    